# Generated by Django 5.0.2 on 2024-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('EC', 'Electronics'), ('KA', 'Kitchen Appliances'), ('BF', 'Bedroom Furniture'), ('HD', 'Home Decor'), ('OE', 'Outdoor Equipment'), ('CA', 'Clothing & Accessories'), ('BP', 'Beauty & Personal Care'), ('SF', 'Sports & Fitness'), ('BS', 'Books & Stationery'), ('TG', 'Toys & Games')], max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
    ]
